server:
  port: 8080

spring:
  application:
    name: collector

  kafka:
    bootstrap-servers: localhost:9092

grpc:
  client:
    collector:
      address: 'static://localhost:9090'
      negotiationType: plaintext